<a href="https://colab.research.google.com/github/bonsoul/Data_Engineering101/blob/main/AND41.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

if 'google.colab' in sys.modules:
    !sudo apt-get update -qq > /dev/null 2>&1
    !sudo apt-get install postgresql -qq > /dev/null 2>&1
    !sudo service postgresql start > /dev/null 2>&1
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '5432';" > /dev/null 2>&1
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

%reload_ext sql
%sql postgresql://postgres:5432@localhost:5432/contoso_100k
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = 0
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

## Categorize

#### High value order if Quantity >= 2 and Netprice >= 20

In [4]:
%%sql


SELECT
         orderdate,
         quantity,
         netprice,
         CASE
                  WHEN quantity >= 2 and netprice >= 50 THEN 'High Value Order'
                  ELSE 'Normal Order'

         END AS order_type
FROM sales
LIMIT 10

    orderdate  quantity  netprice        order_type
0  2015-01-01         1     98.97      Normal Order
1  2015-01-01         1    659.78      Normal Order
2  2015-01-01         2     54.38  High Value Order
3  2015-01-01         4    286.69  High Value Order
4  2015-01-01         7    135.75  High Value Order
5  2015-01-01         3    434.30  High Value Order
6  2015-01-01         1     58.73      Normal Order
7  2015-01-01         3     74.99  High Value Order
8  2015-01-01         2    113.57  High Value Order
9  2015-01-01         1    499.45      Normal Order

### Single High Value if the netprice >= 100

In [7]:
%%sql
SELECT
    orderdate,
    quantity,
    netprice,
    CASE
        WHEN quantity >= 2 AND netprice >= 50  THEN 'High Value Order'
        WHEN quantity = 1  AND netprice >= 100 THEN 'Single High Value'
        ELSE 'Normal Order'
    END AS order_type
FROM sales
LIMIT 10

    orderdate  quantity  netprice         order_type
0  2015-01-01         1     98.97       Normal Order
1  2015-01-01         1    659.78  Single High Value
2  2015-01-01         2     54.38   High Value Order
3  2015-01-01         4    286.69   High Value Order
4  2015-01-01         7    135.75   High Value Order
5  2015-01-01         3    434.30   High Value Order
6  2015-01-01         1     58.73       Normal Order
7  2015-01-01         3     74.99   High Value Order
8  2015-01-01         2    113.57   High Value Order
9  2015-01-01         1    499.45  Single High Value

### MULTIPLE  Standard Items quantity >= 2

In [11]:
%%sql
SELECT
    orderdate,
    quantity,
    netprice,
    CASE
        WHEN quantity >= 2 AND netprice >= 50  THEN 'High Value Order'
        WHEN quantity = 1  AND netprice >= 100 THEN 'Single High Value'
        WHEN quantity >= 2    THEN 'Multiple Standard Items'
        ELSE 'Normal Order'
    END AS order_type
FROM sales
LIMIT 10

    orderdate  quantity  netprice         order_type
0  2015-01-01         1     98.97       Normal Order
1  2015-01-01         1    659.78  Single High Value
2  2015-01-01         2     54.38   High Value Order
3  2015-01-01         4    286.69   High Value Order
4  2015-01-01         7    135.75   High Value Order
5  2015-01-01         3    434.30   High Value Order
6  2015-01-01         1     58.73       Normal Order
7  2015-01-01         3     74.99   High Value Order
8  2015-01-01         2    113.57   High Value Order
9  2015-01-01         1    499.45  Single High Value