<a href="https://colab.research.google.com/github/bonsoul/Data_Engineering101/blob/main/Cohort1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

if 'google.colab' in sys.modules:
    !sudo apt-get update -qq > /dev/null 2>&1
    !sudo apt-get install postgresql -qq > /dev/null 2>&1
    !sudo service postgresql start > /dev/null 2>&1
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '5432';" > /dev/null 2>&1
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

%reload_ext sql
%sql postgresql://postgres:5432@localhost:5432/contoso_100k
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = 0
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [7]:
%%sql


SELECT
       customerkey,
       EXTRACT(YEAR FROM (MIN(orderdate) OVER (PARTITION BY customerkey))) AS cohort_year,
       EXTRACT(YEAR FROM orderdate) AS purchase_year
FROM
        sales
LIMIT 10

   customerkey cohort_year purchase_year
0           15        2021          2021
1          180        2018          2018
2          180        2018          2023
3          180        2018          2023
4          185        2019          2019
5          243        2016          2016
6          387        2018          2018
7          387        2018          2018
8          387        2018          2018
9          387        2018          2018

In [13]:
%%sql

WITH cohort_year AS (

SELECT DISTINCT
       customerkey,
       EXTRACT(YEAR FROM (MIN(orderdate) OVER (PARTITION BY customerkey))) AS cohort_year,
       EXTRACT(YEAR FROM orderdate) AS purchase_year
FROM
        sales
)

SELECT DISTINCT
       cohort_year,
       purchase_year,
       COUNT(customerkey)  OVER (PARTITION BY cohort_year, purchase_year) AS num_customers
FROM
        cohort_year
ORDER BY
        cohort_year,
        purchase_year

   cohort_year purchase_year  num_customers
0         2015          2015           2825
1         2015          2016            126
2         2015          2017            149
3         2015          2018            348
4         2015          2019            388
5         2015          2020            171
6         2015          2021            295
7         2015          2022            600
8         2015          2023            499
9         2015          2024            146
10        2016          2016           3397
11        2016          2017            174
12        2016          2018            374
13        2016          2019            457
14        2016          2020            205
15        2016          2021            336
16        2016          2022            746
17        2016          2023            573
18        2016          2024            183
19        2017          2017           4068
20        2017          2018            473
21        2017          2019            570
22        2017          2020            251
23        2017          2021            450
24        2017          2022            943
25        2017          2023            738
26        2017          2024            246
27        2018          2018           7446
28        2018          2019           1081
29        2018          2020            475
30        2018          2021            779
31        2018          2022           1644
32        2018          2023           1407
33        2018          2024            426
34        2019          2019           7755
35        2019          2020            523
36        2019          2021            873
37        2019          2022           1700
38        2019          2023           1439
39        2019          2024            370
40        2020          2020           3031
41        2020          2021            358
42        2020          2022            694
43        2020          2023            547
44        2020          2024            163
45        2021          2021           4663
46        2021          2022           1051
47        2021          2023            889
48        2021          2024            268
49        2022          2022           9010
50        2022          2023           1764
51        2022          2024            561
52        2023          2023           5890
53        2023          2024            332
54        2024          2024           1402

In [15]:
%%sql


SELECT
         customerkey,
         AVG(quantity * netprice * exchangerate) AS net_revenue,
         COUNT(*) OVER (PARTITION BY customerkey) AS num_purchases
FROM
        sales
GROUP BY
        customerkey
LIMIT 10

   customerkey  net_revenue  num_purchases
0           15      2217.41              1
1          180       836.74              1
2          185      1395.52              1
3          243       287.67              1
4          387       517.32              1
5          406      1096.71              1
6          545       591.91              1
7          649       677.18              1
8          668       162.29              1
9          688      3381.81              1

In [22]:
%%sql

WITH customer_orders AS (
SELECT
         customerkey,
         quantity * netprice * exchangerate AS net_revenue,
         COUNT(*) OVER (PARTITION BY customerkey) AS total_purchases
FROM
        sales
)

SELECT
        customerkey,
        total_purchases,
        AVG(net_revenue) AS avg_net_revenue
FROM
        customer_orders
GROUP BY
        customerkey, total_purchases
LIMIT 10

   customerkey  total_purchases  avg_net_revenue
0           15                1          2217.41
1          180                3           836.74
2          185                1          1395.52
3          243                1           287.67
4          387                9           517.32
5          406                2          1096.71
6          545                6           591.91
7          649                6           677.18
8          668                1           162.29
9          688                5          3381.81