<a href="https://colab.research.google.com/github/bonsoul/Data_Engineering101/blob/main/frameclauses.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

if 'google.colab' in sys.modules:
    !sudo apt-get update -qq > /dev/null 2>&1
    !sudo apt-get install postgresql -qq > /dev/null 2>&1
    !sudo service postgresql start > /dev/null 2>&1
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '5432';" > /dev/null 2>&1
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

%reload_ext sql
%sql postgresql://postgres:5432@localhost:5432/contoso_100k
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = 0
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [6]:
%%sql

SELECT
          TO_CHAR(orderdate, 'YYYY-MM') AS month,
          SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
WHERE EXTRACT(YEAR FROM orderdate) = 2023
GROUP BY month
ORDER BY month;

      month  net_revenue
0   2023-01   3664431.34
1   2023-02   4465204.57
2   2023-03   2244316.52
3   2023-04   1162796.16
4   2023-05   2943005.99
5   2023-06   2864500.03
6   2023-07   2337639.34
7   2023-08   2623919.79
8   2023-09   2622774.85
9   2023-10   2551322.61
10  2023-11   2700103.38
11  2023-12   2928550.93

In [7]:
%%sql


WITH monthly_sales AS(
  SELECT
          TO_CHAR(orderdate, 'YYYY-MM') AS month,
          SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
WHERE EXTRACT(YEAR FROM orderdate) = 2023
GROUP BY month
ORDER BY month
)

SELECT
        month,
        net_revenue,
        AVG(net_revenue) OVER (ORDER BY month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS moving_average
FROM monthly_sales
ORDER BY month;

      month  net_revenue  moving_average
0   2023-01   3664431.34      3664431.34
1   2023-02   4465204.57      4064817.96
2   2023-03   2244316.52      3457984.14
3   2023-04   1162796.16      2624105.75
4   2023-05   2943005.99      2116706.22
5   2023-06   2864500.03      2323434.06
6   2023-07   2337639.34      2715048.45
7   2023-08   2623919.79      2608686.39
8   2023-09   2622774.85      2528111.33
9   2023-10   2551322.61      2599339.08
10  2023-11   2700103.38      2624733.61
11  2023-12   2928550.93      2726658.97

In [7]:
%%sql


WITH monthly_sales AS(
  SELECT
          TO_CHAR(orderdate, 'YYYY-MM') AS month,
          SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
WHERE EXTRACT(YEAR FROM orderdate) = 2023
GROUP BY month
ORDER BY month
)

SELECT
        month,
        net_revenue,
        AVG(net_revenue) OVER (ORDER BY month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS moving_average
FROM monthly_sales
ORDER BY month;