<a href="https://colab.research.google.com/github/bonsoul/Data_Engineering101/blob/main/where.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

if 'google.colab' in sys.modules:
    !sudo apt-get update -qq > /dev/null 2>&1
    !sudo apt-get install postgresql -qq > /dev/null 2>&1
    !sudo service postgresql start > /dev/null 2>&1
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '5432';" > /dev/null 2>&1
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

%reload_ext sql
%sql postgresql://postgres:5432@localhost:5432/contoso_100k
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = 0
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [3]:
%%sql

SELECT
         customerkey,
         EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) AS first_year
FROM sales
WHERE orderdate >= '2020-01-01'

        customerkey first_year
0                15       2021
1               180       2023
2               180       2023
3               387       2021
4               387       2021
...             ...        ...
124446      2099697       2022
124447      2099697       2022
124448      2099743       2022
124449      2099743       2022
124450      2099743       2022

[124451 rows x 2 columns]

In [5]:
%%sql

WITH cohort AS (
SELECT
         customerkey,
         EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) AS first_year
FROM sales
)


SELECT *
FROM cohort
WHERE first_year >= '2020'

       customerkey first_year
0               15       2021
1              406       2021
2              406       2021
3              545       2023
4              545       2023
...            ...        ...
81365      2099697       2022
81366      2099697       2022
81367      2099743       2022
81368      2099743       2022
81369      2099743       2022

[81370 rows x 2 columns]

In [7]:
%%sql

SELECT
        customerkey,
        orderdate,
        (quantity * netprice * exchangerate) AS net_revenue,
        COUNT(*) OVER (PARTITION BY customerkey ORDER BY orderdate) AS order_count
FROM sales

        customerkey   orderdate  net_revenue  order_count
0                15  2021-03-08      2217.41            1
1               180  2018-07-28       525.31            1
2               180  2023-08-28        71.36            3
3               180  2023-08-28      1913.55            3
4               185  2019-06-01      1395.52            1
...             ...         ...          ...          ...
199868      2099711  2016-08-13      2067.75            1
199869      2099711  2017-08-14      3940.92            2
199870      2099743  2022-03-17       375.57            2
199871      2099743  2022-03-17        94.05            2
199872      2099743  2023-02-11       598.46            3

[199873 rows x 4 columns]

In [9]:
%%sql

SELECT
        customerkey,
        orderdate,
        (quantity * netprice * exchangerate) AS net_revenue,
        COUNT(*) OVER (PARTITION BY customerkey ORDER BY orderdate) AS order_count,
        AVG((quantity * netprice * exchangerate)) OVER (PARTITION BY customerkey ORDER BY orderdate) AS running_total_revenue

FROM sales
LIMIT 10

   customerkey   orderdate  net_revenue  order_count  running_total_revenue
0           15  2021-03-08      2217.41            1                2217.41
1          180  2018-07-28       525.31            1                 525.31
2          180  2023-08-28      1913.55            3                 836.74
3          180  2023-08-28        71.36            3                 836.74
4          185  2019-06-01      1395.52            1                1395.52
5          243  2016-05-19       287.67            1                 287.67
6          387  2018-12-21       619.77            4                 592.64
7          387  2018-12-21      1608.10            4                 592.64
8          387  2018-12-21        45.62            4                 592.64
9          387  2018-12-21        97.05            4                 592.64

In [12]:
%%sql

SELECT
         ROW_NUMBER() OVER (ORDER BY orderdate) AS row_number,
         *

FROM
        sales
LIMIT 10

,row_number,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,2,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,3,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,4,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,5,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,6,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,7,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,8,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,9,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,10,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [16]:
%%sql

SELECT
         ROW_NUMBER() OVER (ORDER BY orderdate,
         orderkey,
         linenumber
         ) AS row_number,
         *

FROM
        sales

LIMIT 10

,row_number,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,2,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,3,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,4,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,5,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,6,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,7,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,8,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,9,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,10,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [19]:
%%sql

WITH row_numbering AS (
SELECT
         ROW_NUMBER() OVER (ORDER BY orderdate,
         orderkey,
         linenumber
         ) AS row_number,
         *
FROM
        sales

)

SELECT *
FROM row_numbering
WHERE orderdate > '2015-01-01'
LIMIT 10

,row_number,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,26,2000,0,2015-01-02,2015-01-02,1639738,530,1613,5,65.99,59.39,33.65,USD,1.00
1,27,2001,0,2015-01-02,2015-01-15,2085372,999999,2182,2,1237.50,1237.50,410.01,USD,1.00
2,28,2002,0,2015-01-02,2015-01-02,1732602,510,1822,2,22.40,22.40,11.42,USD,1.00
3,29,2002,1,2015-01-02,2015-01-02,1732602,510,49,5,149.96,149.96,68.96,USD,1.00
4,30,2003,0,2015-01-02,2015-01-02,728917,300,1674,2,4.89,4.89,2.49,EUR,0.83
5,31,2003,1,2015-01-02,2015-01-02,728917,300,369,1,1747.50,1555.28,803.60,EUR,0.83
6,32,2004,0,2015-01-02,2015-01-02,1724183,570,1654,2,155.99,155.99,51.68,USD,1.00
7,33,2005,0,2015-01-02,2015-01-02,2054699,480,460,1,749.75,712.26,382.25,USD,1.00
8,34,3000,0,2015-01-03,2015-01-03,1793739,500,108,3,99.74,97.75,45.87,USD,1.00
9,35,3000,1,2015-01-03,2015-01-03,1793739,500,1684,3,11.82,11.00,3.92,USD,1.00

In [ ]:
%%sql